### ISSUE TITLE
Rghost no longer show edit form on upload

### ISSUE THREAD

**Issue by noway** [daodaod/rghost-uploader#1]
This form, which is usually goes by `action="/%uploadid%"` no longer shows up by rghost when javascript is disabled. This is exactly the case with mechanize framework.
So, when you invoking script with any option, that going to use edit form, script gives you an error:

```
Traceback (most recent call last):
  File "rghost.py", line 84, in <module>
    print upload(filename, upload_filename=namespace.upload_filename, upload_params=upload_params)
  File "rghost.py", line 51, in upload
    browser.select_form(predicate=lambda form, uploaded_url=uploaded_url:is_edit_form(form, uploaded_url))
  File "./rghost-uploader/venv/lib/python2.7/site-packages/mechanize/_mechanize.py", line 524, in select_form
    raise FormNotFoundError("no form matching "+description)
mechanize._mechanize.FormNotFoundError: no form matching predicate <function <lambda> at 0x7fc8da6b5938>
```

This error makes script pretty unusable, because most of the options don't work.

**Comment by noway** [comment]
Apparently this was cookie error, not javascript one. More info here: #2
If someone stumbled upon this issue, and somehow it wouldn't in master already, you can retrieve fixed version from [here](https://github.com/noway421/rghost-uploader/tree/fix-ru-to-net-cookies) or [there](https://github.com/noway421/rghost-uploader/tree/improvements)
